/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const MINT_ASSET_DISCRIMINATOR = new Uint8Array([
  84, 175, 211, 156, 56, 250, 104, 118,
]);

export function getMintAssetDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MINT_ASSET_DISCRIMINATOR);
}

export type MintAssetInstruction<
  TProgram extends string = typeof ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS,
  TAccountAssetRegistry extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountDestiny extends string | AccountMeta<string> = string,
  TAccountDestinyAssetTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  TAccountRent extends string | AccountMeta<string> =
    "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAssetRegistry extends string
        ? WritableAccount<TAccountAssetRegistry>
        : TAccountAssetRegistry,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountDestiny extends string
        ? ReadonlyAccount<TAccountDestiny>
        : TAccountDestiny,
      TAccountDestinyAssetTokenAccount extends string
        ? WritableAccount<TAccountDestinyAssetTokenAccount>
        : TAccountDestinyAssetTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type MintAssetInstructionData = {
  discriminator: ReadonlyUint8Array;
  amountTokens: bigint;
};

export type MintAssetInstructionDataArgs = { amountTokens: number | bigint };

export function getMintAssetInstructionDataEncoder(): FixedSizeEncoder<MintAssetInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amountTokens", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MINT_ASSET_DISCRIMINATOR }),
  );
}

export function getMintAssetInstructionDataDecoder(): FixedSizeDecoder<MintAssetInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amountTokens", getU64Decoder()],
  ]);
}

export function getMintAssetInstructionDataCodec(): FixedSizeCodec<
  MintAssetInstructionDataArgs,
  MintAssetInstructionData
> {
  return combineCodec(
    getMintAssetInstructionDataEncoder(),
    getMintAssetInstructionDataDecoder(),
  );
}

export type MintAssetAsyncInput<
  TAccountAssetRegistry extends string = string,
  TAccountMint extends string = string,
  TAccountOwner extends string = string,
  TAccountDestiny extends string = string,
  TAccountDestinyAssetTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  assetRegistry: Address<TAccountAssetRegistry>;
  mint: Address<TAccountMint>;
  owner: TransactionSigner<TAccountOwner>;
  /** CHECK */
  destiny: Address<TAccountDestiny>;
  destinyAssetTokenAccount?: Address<TAccountDestinyAssetTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  rent?: Address<TAccountRent>;
  amountTokens: MintAssetInstructionDataArgs["amountTokens"];
};

export async function getMintAssetInstructionAsync<
  TAccountAssetRegistry extends string,
  TAccountMint extends string,
  TAccountOwner extends string,
  TAccountDestiny extends string,
  TAccountDestinyAssetTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS,
>(
  input: MintAssetAsyncInput<
    TAccountAssetRegistry,
    TAccountMint,
    TAccountOwner,
    TAccountDestiny,
    TAccountDestinyAssetTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  MintAssetInstruction<
    TProgramAddress,
    TAccountAssetRegistry,
    TAccountMint,
    TAccountOwner,
    TAccountDestiny,
    TAccountDestinyAssetTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    assetRegistry: { value: input.assetRegistry ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    owner: { value: input.owner ?? null, isWritable: true },
    destiny: { value: input.destiny ?? null, isWritable: false },
    destinyAssetTokenAccount: {
      value: input.destinyAssetTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.destinyAssetTokenAccount.value) {
    accounts.destinyAssetTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.destiny.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.assetRegistry),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.destiny),
      getAccountMeta(accounts.destinyAssetTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getMintAssetInstructionDataEncoder().encode(
      args as MintAssetInstructionDataArgs,
    ),
    programAddress,
  } as MintAssetInstruction<
    TProgramAddress,
    TAccountAssetRegistry,
    TAccountMint,
    TAccountOwner,
    TAccountDestiny,
    TAccountDestinyAssetTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountRent
  >);
}

export type MintAssetInput<
  TAccountAssetRegistry extends string = string,
  TAccountMint extends string = string,
  TAccountOwner extends string = string,
  TAccountDestiny extends string = string,
  TAccountDestinyAssetTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  assetRegistry: Address<TAccountAssetRegistry>;
  mint: Address<TAccountMint>;
  owner: TransactionSigner<TAccountOwner>;
  /** CHECK */
  destiny: Address<TAccountDestiny>;
  destinyAssetTokenAccount: Address<TAccountDestinyAssetTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  rent?: Address<TAccountRent>;
  amountTokens: MintAssetInstructionDataArgs["amountTokens"];
};

export function getMintAssetInstruction<
  TAccountAssetRegistry extends string,
  TAccountMint extends string,
  TAccountOwner extends string,
  TAccountDestiny extends string,
  TAccountDestinyAssetTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS,
>(
  input: MintAssetInput<
    TAccountAssetRegistry,
    TAccountMint,
    TAccountOwner,
    TAccountDestiny,
    TAccountDestinyAssetTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress },
): MintAssetInstruction<
  TProgramAddress,
  TAccountAssetRegistry,
  TAccountMint,
  TAccountOwner,
  TAccountDestiny,
  TAccountDestinyAssetTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    assetRegistry: { value: input.assetRegistry ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    owner: { value: input.owner ?? null, isWritable: true },
    destiny: { value: input.destiny ?? null, isWritable: false },
    destinyAssetTokenAccount: {
      value: input.destinyAssetTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.assetRegistry),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.destiny),
      getAccountMeta(accounts.destinyAssetTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getMintAssetInstructionDataEncoder().encode(
      args as MintAssetInstructionDataArgs,
    ),
    programAddress,
  } as MintAssetInstruction<
    TProgramAddress,
    TAccountAssetRegistry,
    TAccountMint,
    TAccountOwner,
    TAccountDestiny,
    TAccountDestinyAssetTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountRent
  >);
}

export type ParsedMintAssetInstruction<
  TProgram extends string = typeof ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    assetRegistry: TAccountMetas[0];
    mint: TAccountMetas[1];
    owner: TAccountMetas[2];
    /** CHECK */
    destiny: TAccountMetas[3];
    destinyAssetTokenAccount: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
    associatedTokenProgram: TAccountMetas[7];
    rent: TAccountMetas[8];
  };
  data: MintAssetInstructionData;
};

export function parseMintAssetInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMintAssetInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      assetRegistry: getNextAccount(),
      mint: getNextAccount(),
      owner: getNextAccount(),
      destiny: getNextAccount(),
      destinyAssetTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getMintAssetInstructionDataDecoder().decode(instruction.data),
  };
}
