/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS } from "../programs";

/** AmountTooSmall: El monto debe ser mayor a cero. */
export const ANCHOR_RWA_TEMPLATE_ERROR__AMOUNT_TOO_SMALL = 0x1770; // 6000

export type AnchorRwaTemplateError =
  typeof ANCHOR_RWA_TEMPLATE_ERROR__AMOUNT_TOO_SMALL;

let anchorRwaTemplateErrorMessages:
  | Record<AnchorRwaTemplateError, string>
  | undefined;
if (process.env.NODE_ENV !== "production") {
  anchorRwaTemplateErrorMessages = {
    [ANCHOR_RWA_TEMPLATE_ERROR__AMOUNT_TOO_SMALL]: `El monto debe ser mayor a cero.`,
  };
}

export function getAnchorRwaTemplateErrorMessage(
  code: AnchorRwaTemplateError,
): string {
  if (process.env.NODE_ENV !== "production") {
    return (
      anchorRwaTemplateErrorMessages as Record<AnchorRwaTemplateError, string>
    )[code];
  }

  return "Error message not available in production bundles.";
}

export function isAnchorRwaTemplateError<
  TProgramErrorCode extends AnchorRwaTemplateError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS,
    code,
  );
}
