/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedInitializeAssetInstruction,
  type ParsedInitializeInstruction,
  type ParsedMintAssetInstruction,
} from "../instructions";

export const ANCHOR_RWA_TEMPLATE_PROGRAM_ADDRESS =
  "jEXgKE9NWJihHqLVAoXZ4e2TSZ7KkV7kub8j4ojcmZC" as Address<"jEXgKE9NWJihHqLVAoXZ4e2TSZ7KkV7kub8j4ojcmZC">;

export enum AnchorRwaTemplateAccount {
  AssetRegistry,
}

export function identifyAnchorRwaTemplateAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): AnchorRwaTemplateAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 94, 213, 134, 205, 170, 175, 68]),
      ),
      0,
    )
  ) {
    return AnchorRwaTemplateAccount.AssetRegistry;
  }
  throw new Error(
    "The provided account could not be identified as a anchorRwaTemplate account.",
  );
}

export enum AnchorRwaTemplateInstruction {
  Initialize,
  InitializeAsset,
  MintAsset,
}

export function identifyAnchorRwaTemplateInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): AnchorRwaTemplateInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return AnchorRwaTemplateInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([214, 153, 49, 248, 95, 248, 208, 179]),
      ),
      0,
    )
  ) {
    return AnchorRwaTemplateInstruction.InitializeAsset;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([84, 175, 211, 156, 56, 250, 104, 118]),
      ),
      0,
    )
  ) {
    return AnchorRwaTemplateInstruction.MintAsset;
  }
  throw new Error(
    "The provided instruction could not be identified as a anchorRwaTemplate instruction.",
  );
}

export type ParsedAnchorRwaTemplateInstruction<
  TProgram extends string = "jEXgKE9NWJihHqLVAoXZ4e2TSZ7KkV7kub8j4ojcmZC",
> =
  | ({
      instructionType: AnchorRwaTemplateInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: AnchorRwaTemplateInstruction.InitializeAsset;
    } & ParsedInitializeAssetInstruction<TProgram>)
  | ({
      instructionType: AnchorRwaTemplateInstruction.MintAsset;
    } & ParsedMintAssetInstruction<TProgram>);
